[package]
name = "day05"
version = "1.0.0"
authors = ["Eduardo Sánchez <whipshout@gmail.com>"]
description = "Day 05 of advent of code 2021"
edition = "2021"

[lib]
path = "src/lib/mod.rs"

[dependencies]
atoi = "0.4"
nom = "6"
tools = { path = "../tools" }